config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :user_tasks

  root 'pages#index'

end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/user_tasks_controller.rb
class UserTasksController < ApplicationController
  before_action :set_user_task, only: [:show, :edit, :update, :destroy]
  before_action :all_tasks, only: [:index, :create, :update, :destroy]

  # GET /user_tasks
  # GET /user_tasks.json
  def index
  end

  # GET /user_tasks/1
  # GET /user_tasks/1.json
  def show
  end

  # GET /user_tasks/new
  def new
    @user_task = UserTask.new
  end

  # GET /user_tasks/1/edit
  def edit
  end

  # POST /user_tasks
  # POST /user_tasks.json
  def create
    @user_task = UserTask.new(user_task_params)

    respond_to do |format|
      if @user_task.save
        format.html { redirect_to @user_task, notice: 'User task was successfully created.' }
        format.js {}
        format.json { render :show, status: :created, location: @user_task }
      else
        format.html { render :new }
        format.js {render :new }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_tasks/1
  # PATCH/PUT /user_tasks/1.json
  def update
    respond_to do |format|
      if @user_task.update(user_task_params)
        format.html { redirect_to @user_task, notice: 'User task was successfully updated.' }
        format.js{}
        format.json { render :show, status: :ok, location: @user_task }
      else
        format.html { render :edit }
        format.js {render :edit }
        format.json { render json: @user_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_tasks/1
  # DELETE /user_tasks/1.json
  def destroy
    @user_task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'User task was successfully destroyed.' }
      format.js {}
      format.json { head :no_content }
    end
  end

  private

    def all_tasks
      @user_tasks = UserTask.all
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_user_task
      @user_task = UserTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_task_params
      params.require(:user_task).permit(:description, :due)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_tasks_helper.rb
module UserTasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Tasks', user_tasks_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AjaxApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="contanier">
    <%= yield %>
  </div>


</body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/user_tasks/_form.html.erb
<%= simple_form_for(@user_task, remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :due %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_tasks/_user_task.html.erb
<li>
  <%= user_task.description %>
  <%= user_task.due %>
  <%= link_to 'Edit', edit_user_task_path(user_task), remote: true %>
  <%= link_to 'Delete', user_task, remote: true, method: :delete, data:{confirm: 'Are you sure?'} %>
</li>

app/views/user_tasks/create.js.erb
$('#tasks').html('<%= j (render @user_tasks) %>');
$('#task-form').slideUp(350);

app/views/user_tasks/destroy.js.erb
$('#tasks').html('<%= j (render @user_tasks) %>');

app/views/user_tasks/edit.html.erb
<h1>Editing User Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_task %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/edit.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

app/views/user_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New User task', new_user_task_path, remote: true, class: 'btn btn-primary' %>

<div id="task-form">

</div>

<div id="tasks">
  <ul>
    <%= render @user_tasks %>
  </ul>
</div>

app/views/user_tasks/new.html.erb
<h1>New User Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/new.js.erb
$('#task-form')
  .html("<%= j (render 'form') %>")
  .slideDown(350);

app/views/user_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @user_task.description %>
</p>

<p>
  <strong>Due:</strong>
  <%= @user_task.due %>
</p>

<%= link_to 'Edit', edit_user_task_path(@user_task) %> |
<%= link_to 'Back', user_tasks_path %>

app/views/user_tasks/update.js.erb
$('#tasks').html('<%= j (render @user_tasks) %>');
$('#task-form').slideUp(350);